### ISSUE TITLE
[Android Bootcamp] Project 0 - ToDo - Ready for review

### ISSUE THREAD

**Issue by basicsbeauty** [basicsbeauty/ToDo#1]
App is ready, please review, cc to @codepathreview @codepath

Name: Siva Satish

**Comment by nesquena** [comment]
Thanks for submitting the Todo app. Can you please review the section in the prework about [the readme](http://courses.codepath.com/snippets/intro_to_android/prework#heading-4-submitting-the-project) for your project? In particular, check out this [README template](http://courses.codepath.com/snippets/intro_to_android/readme_templates/prework_readme.md?raw=true) and be sure to [include a GIF recorded with LiceCap](http://www.cockos.com/licecap/). Please ping me back here once that's complete.

**Comment by basicsbeauty** [comment]
Thanks for prompt response.

Already uploaded GIF, please check.
https://github.com/basicsbeauty/ToDo/blob/master/README.gif

Will try add Hyperlink of the GIF in README.md.

**Comment by nesquena** [comment]
Siva,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer  learn the practical elements of Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to **schedule a short 10 minute phone conversation** with us. Navigate to [early next week](https://calendar.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU) and choose a 15-minute slot. Let us know if none of those times work. 

With regards to extensions to implement, we are looking for developers with an interest in user experience and product development so be sure to focus on additional functional enhancements and/or improving the user interface of the app.

Once you select a slot, can you make sure to **include best number** to reach you at to the invite? Look forward to chatting soon!

**Comment by nesquena** [comment]
> Already uploaded GIF, please check.
> https://github.com/basicsbeauty/ToDo/blob/master/README.gif Will try add Hyperlink of the GIF in README.md.

Can you adjust your project to use [this README template](http://courses.codepath.com/snippets/intro_to_android/readme_templates/prework_readme.md?raw=true). Your README should contain more than just the GIF.

**Comment by basicsbeauty** [comment]
Thank you again for prompt followup.

Updated README.md to include all details.

Marked all the features developed as "FINISHED" at the start of the list.

**Comment by nesquena** [comment]
Great to see you added a number of additional optionals to the app. Hopefully you found the pre-work project really helpful as an introduction to both the class structure and the Android platform.

After reviewing your project, I'd encourage you to take a look at [this guide on code organization best practices](http://guides.codepath.com/android/Organizing-your-Source-Files) to cleanup your source code. Also, look forward to you adding additional functionality and [iterating on the UI a bit](http://guides.codepath.com/android/Styling-UI-Screens-FAQ). Of course, let me know if you have any questions.

See you next week. We will be sending more details on first session in the next day or two.
