### ISSUE TITLE
[Android Bootcamp] Project 0 - ToDo - SQLite instead of local File

### ISSUE THREAD

**Issue by basicsbeauty** [basicsbeauty/ToDo#2]
Added SQLite support instead of local file, cc, @codepathreview @codepath

**Comment by nesquena** [comment]
Hi Siva,

I would encourage you to move a lot of that code out of the activity and into the SQLiteOpenHelper. Refer to [this guide](http://guides.codepath.com/android/Local-Databases-with-SQLiteOpenHelper#crud-operations-create-read-update-delete) for details. In short, SQL code should never be put inside of an activity and should be tucked away into other classes to maintain encapsulation.

I would also encourage you to add another attribute to the todo item (due date, completion, priority) and explore creating a custom adapter next. You can check out [this guide on code organization best practices](http://guides.codepath.com/android/Organizing-your-Source-Files) to better organize your source code as well.

**Comment by basicsbeauty** [comment]
@nesquena , Thanks for the feedback.

Thought of doing the same when writing the code to move all SQL Code out of Activity.
But couldn't do it due as I wanted to finish the task first and clean it up later.
